// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msg_cmd.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Yy.Protocol {

  /// <summary>Holder for reflection information generated from msg_cmd.proto</summary>
  public static partial class MsgCmdReflection {

    #region Descriptor
    /// <summary>File descriptor for msg_cmd.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgCmdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1tc2dfY21kLnByb3RvEgt5eS5wcm90b2NvbCquCAoOTWVzc2FnZUNvbW1h",
            "bmQSDwoLTVNHX1Vua25vd24QABISCg1NU0dfSGVhcnRCb2R5EPQDEhMKDk1T",
            "R19Yb3JCb2R5UnNwEPUDEhkKFE1TR19TZWN1cml0eUNoZWNrUmVxEPYDEhkK",
            "FE1TR19TZWN1cml0eUNoZWNrUnNwEPcDEhsKFk1TR19VZHBQb3J0UmVnaXN0",
            "ZXJSZXEQ+AMSGwoWTVNHX1VkcFBvcnRSZWdpc3RlclJzcBD5AxIRCgxNU0df",
            "TG9naW5SZXEQ6AcSEQoMTVNHX0xvZ2luUnNwEOkHEhQKD01TR19SZWdpc3Rl",
            "clJlcRDqBxIUCg9NU0dfUmVnaXN0ZXJSc3AQ6wcSFQoQTVNHX1F1aXRMb2dp",
            "blJlcRDsBxIVChBNU0dfUXVpdExvZ2luUnNwEO0HEhYKEU1TR19DcmVhdGVS",
            "b29tUmVxENAPEhYKEU1TR19DcmVhdGVSb29tUnNwENEPEhYKEU1TR19TZWFy",
            "Y2hSb29tUmVxENIPEhYKEU1TR19TZWFyY2hSb29tUnNwENMPEhgKE01TR19T",
            "ZWxmSm9pblJvb21SZXEQ1A8SGAoTTVNHX1NlbGZKb2luUm9vbVJzcBDVDxIY",
            "ChNNU0dfU2VsZlF1aXRSb29tUmVxENYPEhgKE01TR19TZWxmUXVpdFJvb21S",
            "c3AQ1w8SGQoUTVNHX090aGVySm9pblJvb21Sc3AQ2A8SGQoUTVNHX090aGVy",
            "UXVpdFJvb21Sc3AQ2Q8SHgoZTVNHX0dldEVudGVyU2NlbmVUb2tlblJlcRDa",
            "DxIeChlNU0dfR2V0RW50ZXJTY2VuZVRva2VuUnNwENsPEhkKFE1TR19Ccm9h",
            "ZGNhc3RSb29tUmVxEPwREhkKFE1TR19Ccm9hZGNhc3RSb29tUnNwEP0REhMK",
            "Dk1TR19OZXdSb29tUmVxEMQTEhMKDk1TR19OZXdSb29tUnNwEMUTEhYKEU1T",
            "R19EZWxldGVSb29tUmVxEMcTEhYKEU1TR19EZWxldGVSb29tUnNwEMgTEhYK",
            "EU1TR19TY2VuZUxvZ2luUmVxELgXEhYKEU1TR19TY2VuZUxvZ2luUnNwELkX",
            "EhYKEU1TR19DMlNFbnRlclNjZW5lELoXEhYKEU1TR19TMkNFbnRlclNjZW5l",
            "ELsXEhYKEU1TR19DMlNMZWF2ZVNjZW5lELwXEhYKEU1TR19TMkNMZWF2ZVNj",
            "ZW5lEL0XEhAKC01TR19DMlNNb3ZlEL4XEhAKC01TR19TMkNNb3ZlEL8XEhoK",
            "FU1TR19DMlNKdW1wQW5kR3Jhdml0eRDAFxIaChVNU0dfUzJDSnVtcEFuZEdy",
            "YXZpdHkQwRcSGwoWTVNHX0MyU090aGVyUGxheWVyRGF0YRDCFxIbChZNU0df",
            "UzJDT3RoZXJQbGF5ZXJEYXRhEMMXYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Yy.Protocol.MessageCommand), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MessageCommand {
    [pbr::OriginalName("MSG_Unknown")] MsgUnknown = 0,
    /// <summary>
    /// 连接协议相关
    /// </summary>
    [pbr::OriginalName("MSG_HeartBody")] MsgHeartBody = 500,
    [pbr::OriginalName("MSG_XorBodyRsp")] MsgXorBodyRsp = 501,
    [pbr::OriginalName("MSG_SecurityCheckReq")] MsgSecurityCheckReq = 502,
    [pbr::OriginalName("MSG_SecurityCheckRsp")] MsgSecurityCheckRsp = 503,
    [pbr::OriginalName("MSG_UdpPortRegisterReq")] MsgUdpPortRegisterReq = 504,
    [pbr::OriginalName("MSG_UdpPortRegisterRsp")] MsgUdpPortRegisterRsp = 505,
    /// <summary>
    /// 登录模块：网关服->账号服
    /// </summary>
    [pbr::OriginalName("MSG_LoginReq")] MsgLoginReq = 1000,
    [pbr::OriginalName("MSG_LoginRsp")] MsgLoginRsp = 1001,
    [pbr::OriginalName("MSG_RegisterReq")] MsgRegisterReq = 1002,
    [pbr::OriginalName("MSG_RegisterRsp")] MsgRegisterRsp = 1003,
    [pbr::OriginalName("MSG_QuitLoginReq")] MsgQuitLoginReq = 1004,
    [pbr::OriginalName("MSG_QuitLoginRsp")] MsgQuitLoginRsp = 1005,
    /// <summary>
    /// 房间模块：网关服->中心服
    /// </summary>
    [pbr::OriginalName("MSG_CreateRoomReq")] MsgCreateRoomReq = 2000,
    [pbr::OriginalName("MSG_CreateRoomRsp")] MsgCreateRoomRsp = 2001,
    [pbr::OriginalName("MSG_SearchRoomReq")] MsgSearchRoomReq = 2002,
    [pbr::OriginalName("MSG_SearchRoomRsp")] MsgSearchRoomRsp = 2003,
    [pbr::OriginalName("MSG_SelfJoinRoomReq")] MsgSelfJoinRoomReq = 2004,
    [pbr::OriginalName("MSG_SelfJoinRoomRsp")] MsgSelfJoinRoomRsp = 2005,
    [pbr::OriginalName("MSG_SelfQuitRoomReq")] MsgSelfQuitRoomReq = 2006,
    [pbr::OriginalName("MSG_SelfQuitRoomRsp")] MsgSelfQuitRoomRsp = 2007,
    [pbr::OriginalName("MSG_OtherJoinRoomRsp")] MsgOtherJoinRoomRsp = 2008,
    [pbr::OriginalName("MSG_OtherQuitRoomRsp")] MsgOtherQuitRoomRsp = 2009,
    [pbr::OriginalName("MSG_GetEnterSceneTokenReq")] MsgGetEnterSceneTokenReq = 2010,
    [pbr::OriginalName("MSG_GetEnterSceneTokenRsp")] MsgGetEnterSceneTokenRsp = 2011,
    /// <summary>
    /// 房间广播：中心服->网关服
    /// </summary>
    [pbr::OriginalName("MSG_BroadcastRoomReq")] MsgBroadcastRoomReq = 2300,
    [pbr::OriginalName("MSG_BroadcastRoomRsp")] MsgBroadcastRoomRsp = 2301,
    /// <summary>
    /// 房间增删：中心服->逻辑服
    /// </summary>
    [pbr::OriginalName("MSG_NewRoomReq")] MsgNewRoomReq = 2500,
    [pbr::OriginalName("MSG_NewRoomRsp")] MsgNewRoomRsp = 2501,
    [pbr::OriginalName("MSG_DeleteRoomReq")] MsgDeleteRoomReq = 2503,
    [pbr::OriginalName("MSG_DeleteRoomRsp")] MsgDeleteRoomRsp = 2504,
    /// <summary>
    /// 场景模块：逻辑服->客户端
    /// </summary>
    [pbr::OriginalName("MSG_SceneLoginReq")] MsgSceneLoginReq = 3000,
    [pbr::OriginalName("MSG_SceneLoginRsp")] MsgSceneLoginRsp = 3001,
    [pbr::OriginalName("MSG_C2SEnterScene")] MsgC2SenterScene = 3002,
    [pbr::OriginalName("MSG_S2CEnterScene")] MsgS2CenterScene = 3003,
    [pbr::OriginalName("MSG_C2SLeaveScene")] MsgC2SleaveScene = 3004,
    [pbr::OriginalName("MSG_S2CLeaveScene")] MsgS2CleaveScene = 3005,
    [pbr::OriginalName("MSG_C2SMove")] MsgC2Smove = 3006,
    [pbr::OriginalName("MSG_S2CMove")] MsgS2Cmove = 3007,
    [pbr::OriginalName("MSG_C2SJumpAndGravity")] MsgC2SjumpAndGravity = 3008,
    [pbr::OriginalName("MSG_S2CJumpAndGravity")] MsgS2CjumpAndGravity = 3009,
    [pbr::OriginalName("MSG_C2SOtherPlayerData")] MsgC2SotherPlayerData = 3010,
    [pbr::OriginalName("MSG_S2COtherPlayerData")] MsgS2CotherPlayerData = 3011,
  }

  #endregion

}

#endregion Designer generated code
