// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: player.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace yy.protocol.app
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerID : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public uint Uid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerBaseData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public uint Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sockfd")]
        public int Sockfd { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"state")]
        public int State { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"hp_current")]
        public int HpCurrent { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"hp_max")]
        public int HpMax { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"position")]
        public byte[] Position { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"rotation")]
        public byte[] Rotation { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"ani_speed")]
        public float AniSpeed { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"ani_isJump")]
        public bool aniisJump { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"ani_isGround")]
        public bool aniisGround { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"ani_isFreeFall")]
        public bool aniisFreeFall { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"ani_motionSpeed")]
        public float animotionSpeed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerMove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public uint Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"position")]
        public byte[] Position { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"rotation")]
        public byte[] Rotation { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"move_target")]
        public byte[] MoveTarget { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"ani_speed")]
        public float AniSpeed { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"ani_motionSpeed")]
        public float animotionSpeed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerJumpAndGravity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public uint Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ani_isJump")]
        public bool aniisJump { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ani_isGround")]
        public bool aniisGround { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ani_isFreeFall")]
        public bool aniisFreeFall { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"result")]
        public bool Result { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"selfdata")]
        public PlayerBaseData Selfdata { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"othersdata")]
        public global::System.Collections.Generic.List<PlayerBaseData> Othersdatas { get; } = new global::System.Collections.Generic.List<PlayerBaseData>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
